name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      CONTAINER_NAME: docker-overlord
      CONTAINER_HASH: ${GITHUB_SHA:7}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USERNAME/$CONTAINER_NAME:$CONTAINER_HASH
    
    - name: Set up Docker Hub
      run: echo $DOCKER_TOKEN | docker login --username=$DOCKER_USERNAME --password-stdin
    
    - name: Push to Docker Hub
      run: docker push $DOCKER_USERNAME/$CONTAINER_NAME:$CONTAINER_HASH
